# Run Roles
- hosts: work
  become: true
  roles:
     - work
     - base

- hosts: raspberry
  become: true
  roles:
     - raspberry

- hosts: private
  become: true
  roles:
     - base
     - private
