---
- name: Start MariaDB
  service:
    name: mariadb
    state: started

- name: Restart SSH
  service:
    name: sshd
    state: restarted

- name: Start NTP
  service:
    name: ntp
    state: started