- name: Create Group
  ansible.builtin.group:
    name: nserbin
    state: present

- name: Create User
  ansible.builtin.user:
    name: nserbin
    group: nserbin
    groups: sudo, docker
    state: present
    shell: /bin/zsh
