- name: Setting Pacman Mirror
  shell: pacman-mirrors --country chile --api --protocols all --set-branch stable && sudo pacman -Syyu
- name: Set Time Zone
  timezone: 
    name: America/Argentina/Buenos_Aires
- name: Adjust current Swappiness
  tags: swappiness,sysctl,system,setup
  lineinfile:
    dest: "/etc/sysctl.conf"
    create: yes
    regexp: "swappiness ="
    line: "vm.swappiness = 1"
  register: swappiness

#- name: Apply Swappiness
#  tags: swappiness,sysctl,system,setup
#  command: sysctl vm.swappiness= 1
#  when: swappiness.changed
