- name: Remove Unwanted Programs
  apt:
    name:
      - cherrytree
      - firefox
      - firefox-esr
      - mate-terminal
      - mc
      - nautilus
      - neovim
      - vim
      - xterm
      - uxterm
    state: absent
    purge: yes
- name: Delete Unwanted Programs Folders  
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/bin/cherrytree
    - /bin/cherrytree
    - /etc/firefox-esr/
    - /etc/firefox
    - /usr/bin/mate-terminal
    - /usr/bin/mc
    - /usr/bin/uxterm
    - /usr/bin/vim
    - /usr/bin/xterm