- name: Adding Brave Apt signing key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
- name: Add Brave Repository
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
    filename: brave-browser-release
    update_cache: true
- name: Add Kali Linux Repository
  apt_repository:
    repo: deb [arch=amd64] http://http.kali.org/kali kali-rolling main non-free contrib
    state: present
    filename: kali-tools
    update_cache: true
  when: ansible_distribution == "Kali GNU/Linux"
- name: Add Kali Linux src Repository
  apt_repository:
    repo: deb-src http://http.kali.org/kali kali-rolling main non-free contrib
    state: present
    update_cache: true
  when: ansible_distribution == "Kali GNU/Linux"
- name: Add Parrot Linux Repository
  apt_repository:
    repo: deb [arch=amd64] https://mirror.parrot.sh/mirrors/parrot/ rolling main contrib non-free
    state: present
    filename: Parrot-os-tools
    update_cache: true
  when: ansible_distribution == "Parrot GNU/Linux"
- name: Add Parrot Linux src Repository
  apt_repository:
    repo: deb-src https://mirror.parrot.sh/mirrors/parrot/ rolling main contrib non-free
    state: present
    update_cache: true
  when: ansible_distribution == "Parrot GNU/Linux"
- name: Add Parrot Linux Security Repository
  apt_repository:
    repo: deb [arch=amd64] https://mirror.parrot.sh/mirrors/parrot/ rolling-security main contrib non-free
    state: present
    filename: Parrot-os-security-tools
    update_cache: true
  when: ansible_distribution == "Parrot GNU/Linux"
- name: Add Parrot Linux Security src Repository
  apt_repository:
    repo: deb-src https://mirror.parrot.sh/mirrors/parrot/ rolling-security main contrib non-free
    state: present
    update_cache: true
  when: ansible_distribution == "Parrot GNU/Linux"