- name: Add en_US locale
  tags: locale,system,setup
  locale_gen:
    name: en_US.UTF-8
    state: present
- name: Add es_AR locale
  tags: locale,system,setup
  locale_gen:
    name: es_AR.UTF-8
    state: present

- name: Set Spanish locale
  tags: locale,system,setup
  locale_gen:
    name: es_AR.UTF-8
    state: present
  register: locale
- name: Set es_AR as default locale
  tags: locale,system,setup
  command: localectl set-locale LANG=es_AR.UTF-8
  when: locale.changed